#!/bin/bash
case $BLOCK_BUTTON in
	1) CAL_WIDTH=$(( $(cal -n 1 | head -1 | wc -c) + 1 ))
	   xterm -fa 'Roboto Mono' -fs 9  -geometry ${CAL_WIDTH}x10-0+50 -T "CAL" -e sh /home/bjew/Packages/cal/cal.sh 1;;

	3) CAL_WIDTH=$(( $(cal -n 2 | head -1 | wc -c) + 1 ))
	   xterm -fa 'Roboto Mono' -fs 9  -geometry ${CAL_WIDTH}x10-0+50 -T "CAL" -e sh /home/bjew/Packages/cal/cal.sh 2;;
esac

date '+%I:%M %p '
