#!/bin/bash

VOLUME=$(pacmd info | grep -oE '[0-9]{1,3}%' | head -1 | grep -oE '[0-9]{1,3}')
COLOR=#ffffff

if grep -q RUNNING /proc/asound/card*/*p/*/status 2>&1; then
	COLOR="#aeffa8"
else
	COLOR="#ffffff"
fi

MUTED=$(pacmd dump | awk '
	$1 == "set-sink-mute" {m[$2] = $3}
	$1 == "set-default-sink" {s = $2}
	END {print m[s]}')

if [[ "$MUTED" = "yes" ]] ; then
	COLOR="#f44242"
fi

case $BLOCK_BUTTON in
	1) echo "<span color='$COLOR'>$VOLUME%</span>" && exit;;
	3) xdotool key Super_L+o;;
esac

if [[ $VOLUME -eq 0 ]] ; then
	echo "<span color='$COLOR'></span>"
elif [[ $VOLUME -lt 25 ]]; then
	echo "<span color='$COLOR'></span>"
else
	echo "<span color='$COLOR'></span>"
fi
