#!/bin/bash
EXTERNAL_OUTPUT="DP1"
INTERNAL_OUTPUT="eDP1"

# if we don't have a file, start at zero
if [ ! -f "/tmp/monitor_mode.dat" ] ; then
  monitor_mode="all"
else
  monitor_mode=`cat /tmp/monitor_mode.dat`
fi

if [ $monitor_mode = "EXTERNAL" ]; then
        google-chrome-stable --disk-cache-dir=/dev/null --force-device-scale-factor=1.3
else
        google-chrome-stable --disk-cache-dir=/dev/null --force-device-scale-factor=1.9
fi
